In [1]:
import tensorflow as tf
import numpy as np

In [2]:
np.random.seed(80)
tf.set_random_seed(80)

In [3]:
rand_a=np.random.uniform(0,79,(3,2))

In [13]:
rand_b=np.random.uniform(0,34,(3,2))

In [14]:
rand_b

array([[28.75727166,  6.80422063],
       [27.60948074, 12.67985089],
       [27.52780219,  0.40783893]])

In [15]:
a=tf.placeholder(tf.float32)

In [16]:
b=tf.placeholder(tf.float32)

In [17]:
add=a+b

In [18]:
mul=a+b

In [19]:
with tf.Session() as sess:
    addres=sess.run(add,feed_dict={a:rand_a,b:rand_b})
    print(addres)
    print("\n")
    mult=sess.run(mul,feed_dict={a:rand_a,b:rand_b})
    print(mult)

[[69.98862  62.057323]
 [48.92913  65.96392 ]
 [99.265495 54.534706]]


[[69.98862  62.057323]
 [48.92913  65.96392 ]
 [99.265495 54.534706]]
